### ISSUE TITLE
[BUG] Cannot update metadata (probably due to different date formats between app and the server)

### ISSUE THREAD

**Issue by bbqf** [astubenbord/paperless-mobile#169]
**Describe the bug**
Cannot update metadata of a document, like adding tags. 

I assume this is due to the fact, that the date format of the server (paperless-ngx 1.8.0) is German: (settings on the web-interface:  Medium: 11.05.2023) and my smart phone, Android, using English locale, so at least displayed dates are like "May 8, 2023".

**To Reproduce**
1. Open an existing document
2. Click on 'Edit'
3. Add a tag
4. Click 'Save changes'
5. Nothing happens, changes are reverted.

**Expected behavior**
Changes get saved

**Screenshots**
Paperless log:
[2023-05-11 17:05:11,828] [ERROR] [django.request] Internal Server Error: /paperless/api/documents/2239/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/paperless/src/documents/views.py", line 231, in update
    response = super().update(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/usr/src/paperless/src/documents/serialisers.py", line 243, in update
    validated_data.pop("created_date")
KeyError: 'created_date'

**Device Information:**
 - Device: Samsung Galaxy S22
 - OS: Android 13
 - Paperless Mobile version: 2.1.0+27
 - Paperless Server version: 1.8.0 (API v2)

**Additional context**
Paperless Web UI works flawlessly.

**Comment by astubenbord** [comment]
Paperless mobile does not make use of the web client date settings. The date is sent to the server as an ISO 8601 encoded string and is therefore independent of the displayed format. I remember a while ago some others also had a similar issue with an older version of paperless when uploading documents. There was a fix in a later version, but not sure when exactly that was and if it's related. But it seems like this is something different. See #70, #72

**Comment by bbqf** [comment]
Here's some more data: I an app version 2.2.4+32, switched the debugging on the server and guess what - PUT request doesn't even get to the server, mobile app stays in the dialog with "Save changes" button, clicking it doesn't do anything at all, the dialog stays open.
Question 1: Can I somehow enable logging within the app? I don't have a problem connecting to my phone with adb, just to be sure :)
Question 2: How can I get an old version 2.1.0 back? I entered beta program, maybe that's how I got 2.2.4, I guess, but now, I left beta, uninstalled, and still getting 2.2.4.

**Comment by astubenbord** [comment]
Yeah, this is expected, but I got most of the main features working again. I will publish an update today. But it's still WIP.

**Comment by astubenbord** [comment]
Should be fixed in 2.2.5. Should be available today.

**Comment by bbqf** [comment]
OK, I will give it a try, otherwise with the version 2.1.0 here's what adb log has to say:
05-12 12:13:39.957 18767 18795 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
05-12 12:13:39.957 18767 18795 E flutter : #0      PaperlessDocumentsApiImpl.update (package:paperless_api/src/modules/documents_api/paperless_documents_api_impl.dart:81)
05-12 12:13:39.957 18767 18795 E flutter : <asynchronous suspension>
05-12 12:13:39.957 18767 18795 E flutter : #1      DocumentEditCubit.updateDocument (package:paperless_mobile/features/document_edit/cubit/document_edit_cubit.dart:68)
05-12 12:13:39.957 18767 18795 E flutter : <asynchronous suspension>
05-12 12:13:39.957 18767 18795 E flutter : #2      _DocumentEditPageState._onSubmit (package:paperless_mobile/features/document_edit/view/document_edit_page.dart:290)
05-12 12:13:39.957 18767 18795 E flutter : <asynchronous suspension>
05-12 12:13:39.957 18767 18795 E flutter : 

Server log with PAPERLESS_DEBUG=true doesn't have much more data:
Internal Server Error: /paperless/api/documents/2239/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/paperless/src/documents/views.py", line 231, in update
    response = super().update(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/usr/src/paperless/src/documents/serialisers.py", line 243, in update
    validated_data.pop("created_date")
KeyError: 'created_date'
[2023-05-12 12:05:21,807] [ERROR] [django.request] Internal Server Error: /paperless/api/documents/2239/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/paperless/src/documents/views.py", line 231, in update
    response = super().update(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/usr/src/paperless/src/documents/serialisers.py", line 243, in update
    validated_data.pop("created_date")
KeyError: 'created_date'

**Comment by astubenbord** [comment]
Yeah I had this aswell. I use freezed sealed classes for some types now and I forgot to adapt that. That's already fixed in the next release. Thanks for reporting.

**Comment by astubenbord** [comment]
Fixed in https://github.com/astubenbord/paperless-mobile/releases/tag/v2.2.5.

**Comment by thwcz** [comment]
Hey guy,

I fear, that one's back. My instance works great via Browser. But no chance updating a Doc via Android. Neither via Proxy nor direct via IP.
