### ISSUE TITLE
[Bug]: Cant upload image: type 'int' is not a subtype of type 'List<dynamic>? 

### ISSUE THREAD

**Issue by Alexandero89** [astubenbord/paperless-mobile#294]
### What happened?

I cant take a picture and upload it to a paperless instance.
I installed the last app version from the google play store, logged in, took a picture in the scanner app, cropped it and clicked on "upload all".
Now the button text changes to "uploading" with the "in progress" icon inside the button and hangs there.
Nothing happens from this point on.
Also tried to enable the setting "convert to pdf before upload", but did not help.

NOTE:
The attached log output is shortened.
The first error "type 'int' is not a subtype of type 'List<dynamic>?' in type cast" only appears once.
After this one the error "RangeError (index): Invalid value: Not in inclusive range X..X: X" appears infinitely often.
It seems there is a while loop which is executing a function and this function is throwing an exception.
Because all this million RangeError Errors are thrown in the same second.

Maybe thats why the upload is hanging? Maybe a deadloop inside this logging function?

### Steps to reproduce

1. Install App
2. Login to custom server in local network (http://foobar:8000)
3. Go to Scanner Tab and take a picture of a document
4. Click on upload all

### Log output from the app

```shell
2023-10-30 21:54:26.815	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
file not in PDF format or corrupted
---END ERROR---
---BEGIN STACKTRACE---

---END STACKTRACE---
2023-10-30 21:54:44.689	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
type 'int' is not a subtype of type 'List<dynamic>?' in type cast
---END ERROR---
---BEGIN STACKTRACE---
#0      new PaperlessServerStatisticsModel.fromJson (package:paperless_api/src/models/paperless_server_statistics_model.dart:17)
#1      PaperlessServerStatsApiImpl.getServerStatistics (package:paperless_api/src/modules/server_stats_api/paperless_server_stats_api_impl.dart:50)
<asynchronous suspension>

---END STACKTRACE---
2023-10-30 21:54:56.517	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2023-10-30 21:54:56.565	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
type 'int' is not a subtype of type 'List<dynamic>?' in type cast
---END ERROR---
---BEGIN STACKTRACE---
#0      new PaperlessServerStatisticsModel.fromJson (package:paperless_api/src/models/paperless_server_statistics_model.dart:17)
#1      PaperlessServerStatsApiImpl.getServerStatistics (package:paperless_api/src/modules/server_stats_api/paperless_server_stats_api_impl.dart:50)
<asynchronous suspension>
#2      InboxCubit.refreshItemsInInboxCount (package:paperless_mobile/features/inbox/cubit/inbox_cubit.dart:85)
<asynchronous suspension>

---END STACKTRACE---
2023-10-30 21:54:56.570	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
RangeError (index): Invalid value: Only valid value is 0: 1
---END ERROR---
---BEGIN STACKTRACE---
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ParsedErrorLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:50)
#2      ParsedFormattedLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:123)
#3      ParsedLogMessage.parse (package:paperless_mobile/features/logging/models/parsed_log_message.dart:15)
#4      AppLogsCubit._updateLogsFromFile (package:paperless_mobile/features/logging/cubit/app_logs_cubit.dart:68)
<asynchronous suspension>

---END STACKTRACE---
2023-10-30 21:54:56.632	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
RangeError (index): Invalid value: Not in inclusive range 0..2: 3
---END ERROR---
---BEGIN STACKTRACE---
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ParsedErrorLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:55)
#2      ParsedFormattedLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:123)
#3      ParsedLogMessage.parse (package:paperless_mobile/features/logging/models/parsed_log_message.dart:15)
#4      AppLogsCubit._updateLogsFromFile (package:paperless_mobile/features/logging/cubit/app_logs_cubit.dart:68)
<asynchronous suspension>

---END STACKTRACE---
2023-10-30 21:54:56.634	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
RangeError (index): Invalid value: Not in inclusive range 0..2: 3
---END ERROR---
---BEGIN STACKTRACE---
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ParsedErrorLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:55)
#2      ParsedFormattedLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:123)
#3      ParsedLogMessage.parse (package:paperless_mobile/features/logging/models/parsed_log_message.dart:15)
#4      AppLogsCubit._updateLogsFromFile (package:paperless_mobile/features/logging/cubit/app_logs_cubit.dart:68)
<asynchronous suspension>

---END STACKTRACE---
2023-10-30 21:54:56.637	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
RangeError (index): Invalid value: Not in inclusive range 0..3: 4
---END ERROR---
---BEGIN STACKTRACE---
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ParsedErrorLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:61)
#2      ParsedFormattedLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:123)
#3      ParsedLogMessage.parse (package:paperless_mobile/features/logging/models/parsed_log_message.dart:15)
#4      AppLogsCubit._updateLogsFromFile (package:paperless_mobile/features/logging/cubit/app_logs_cubit.dart:68)
<asynchronous suspension>

---END STACKTRACE---
2023-10-30 21:54:56.638	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
RangeError (index): Invalid value: Not in inclusive range 0..3: 4
---END ERROR---
---BEGIN STACKTRACE---
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ParsedErrorLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:61)
#2      ParsedFormattedLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:123)
#3      ParsedLogMessage.parse (package:paperless_mobile/features/logging/models/parsed_log_message.dart:15)
#4      AppLogsCubit._updateLogsFromFile (package:paperless_mobile/features/logging/cubit/app_logs_cubit.dart:68)
<asynchronous suspension>

---END STACKTRACE---
2023-10-30 21:54:56.641	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
RangeError (index): Invalid value: Not in inclusive range 0..10: 11
---END ERROR---
---BEGIN STACKTRACE---
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ParsedErrorLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:61)
#2      ParsedFormattedLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:123)
#3      ParsedLogMessage.parse (package:paperless_mobile/features/logging/models/parsed_log_message.dart:15)
#4      AppLogsCubit._updateLogsFromFile (package:paperless_mobile/features/logging/cubit/app_logs_cubit.dart:68)
<asynchronous suspension>

---END STACKTRACE---
2023-10-30 21:54:56.643	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
RangeError (index): Invalid value: Not in inclusive range 0..10: 11
---END ERROR---
---BEGIN STACKTRACE---
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ParsedErrorLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:61)
#2      ParsedFormattedLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:123)
#3      ParsedLogMessage.parse (package:paperless_mobile/features/logging/models/parsed_log_message.dart:15)
#4      AppLogsCubit._updateLogsFromFile (package:paperless_mobile/features/logging/cubit/app_logs_cubit.dart:68)
<asynchronous suspension>

---END STACKTRACE---
2023-10-30 21:54:56.660	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
RangeError (index): Invalid value: Only valid value is 0: 1
---END ERROR---
---BEGIN STACKTRACE---
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ParsedErrorLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:50)
#2      ParsedFormattedLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:123)
#3      ParsedLogMessage.parse (package:paperless_mobile/features/logging/models/parsed_log_message.dart:15)
#4      AppLogsCubit._updateLogsFromFile (package:paperless_mobile/features/logging/cubit/app_logs_cubit.dart:68)
<asynchronous suspension>

---END STACKTRACE---
2023-10-30 21:54:56.662	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
RangeError (index): Invalid value: Not in inclusive range 0..1: 2
---END ERROR---
---BEGIN STACKTRACE---
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ParsedErrorLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:50)
#2      ParsedFormattedLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:123)
#3      ParsedLogMessage.parse (package:paperless_mobile/features/logging/models/parsed_log_message.dart:15)
#4      AppLogsCubit._updateLogsFromFile (package:paperless_mobile/features/logging/cubit/app_logs_cubit.dart:68)
<asynchronous suspension>

---END STACKTRACE---
```

### Paperless-ng*x Version

1.17.4

### Paperless-Mobile Version

3.1.1

### Device

Poco x3 pro

### Operating System Version

CrDroid 9.10

### Device Locale

german

### Selected Locale

German

**Comment by Alexandero89** [comment]
I asked chatgpt about this problem and here is the suggestion.
Dont know if it helps:


The error message suggests that there is a type mismatch in the `fromJson` constructor of the `PaperlessServerStatisticsModel` class. Specifically, the `json['document_file_type_counts']` value is being cast to a `List<dynamic>?`, but it may not actually be a list of dynamic objects.

To fix this error, you can add a null check before casting the value to a list. Here's an updated version of the `PaperlessServerStatisticsModel` class with the null check added:

```
class PaperlessServerStatisticsModel {
  final int documentsTotal;
  final int documentsInInbox;
  final int? totalChars;
  final List<DocumentFileTypeCount> fileTypeCounts;
  PaperlessServerStatisticsModel({
    required this.documentsTotal,
    required this.documentsInInbox,
    this.totalChars,
    this.fileTypeCounts = const [],
  });

  PaperlessServerStatisticsModel.fromJson(Map<String, dynamic> json)
      : documentsTotal = json['documents_total']?? 0,
        documentsInInbox = json['documents_inbox']?? 0,
        totalChars = json["character_count"],
        fileTypeCounts = (json['document_file_type_counts'] as List<dynamic>??? [])
           .map((e) => DocumentFileTypeCount.fromJson(e))
           .toList();
}

class DocumentFileTypeCount {
  final String mimeType;
  final int count;

  DocumentFileTypeCount({
    required this.mimeType,
    required this.count,
  });

  DocumentFileTypeCount.fromJson(Map<String, dynamic> json)
      : mimeType = json['mime_type'],
        count = json['mime_type_count'];
}
```

In this updated version, the `json['document_file_type_counts']` value is cast to a `List<dynamic>?` with a null check before casting. If the value is null, an empty list is created instead of throwing a type cast error.

**Comment by astubenbord** [comment]
Hi, you are probably correct, I assume that a malformed message is logged which is then incorrectly parsed. 
In the current implementation a null check is already in place though. Could you give me the output of /api/statistics/ of your server?

**Comment by Alexandero89** [comment]
Hey @astubenbord ,

thank you very much for the fast response.

I get an 404 when requesting /api/statistics.
I also cant find the the api path to be mentioned in [https://docs.paperless-ngx.com/api/](https://docs.paperless-ngx.com/api/)

Do you maybe mean something else? Or was it removed in some of the last updates?

**Comment by astubenbord** [comment]
Make sure to include the trailing slash

**Comment by Alexandero89** [comment]
You are absolutely correct!

Here the response:
```
*   Trying 192.168.178.32:8000...
* Connected to 192.168.178.32 (192.168.178.32) port 8000 (#0)
> GET /api/statistics/ HTTP/1.1
> Host: 192.168.178.32:8000
> User-Agent: curl/8.0.1
> Accept: */*
> Cookie: csrftoken=foo; sessionid=bar
> 
< HTTP/1.1 200 OK
< Server: nginx/1.24.0
< Date: Mon, 30 Oct 2023 19:52:31 GMT
< Content-Type: application/json
< Content-Length: 114
< Connection: keep-alive
< vary: Accept, Accept-Language, origin, Cookie
< allow: GET, HEAD, OPTIONS
< x-frame-options: SAMEORIGIN
< x-api-version: 3
< x-version: 1.17.4
< content-language: en-us
< x-content-type-options: nosniff
< referrer-policy: same-origin
< cross-origin-opener-policy: same-origin
< P3P: CP=""
< 
* Connection #0 to host 192.168.178.32 left intact
{"documents_total":0,"documents_inbox":null,"inbox_tag":null,"document_file_type_counts":0,"character_count":null}%  
```

FYI: The paperless server is freshly setup. so there are no documents right now.

**Comment by astubenbord** [comment]
Okay, that's weird. I would expect an empty list to be returned there. I've asked the developers. I'll report back once I've got more information.

**Comment by Alexandero89** [comment]
Thanks for your effort.
Awesome work from you!

**Comment by astubenbord** [comment]
They already fixed it :)
https://github.com/paperless-ngx/paperless-ngx/pull/4464

However, that doesn't change the fact that there is an issue with the log message parsing. I'll have a look in the next days

**Comment by astubenbord** [comment]
I found the error in code, will be fixed in the next update.

**Comment by Alexandero89** [comment]
Really appreciate your fast help and two of your mentioned bugs are indeed fixed.

I am running the dev branch of paperless-ngx and build the paperless-mobile app with the last commit.
The "`type 'int' is not a subtype of type 'List<dynamic>?' in type cast`" and the "`RangeError (index): Invalid value: Not in inclusive range 0..2: 3`" are gone, but the app still is not uploading a picture i take by myself.

I could triage the problem and find out that every media file i got from external sources (received by messenger, downloaded from website etc etc) is working.
Its only hanging and not uploading when i try to upload a picture i took with my phone. 
Does not matter if i use the paperless-mobile app to take the picture or any other camera app.

Fun fact: when i send the exact same picture via whatsapp and then download the same picture from whatsapp and upload it to paperless its working.

Could not find out what exactly is wrong with native pictures. Only error message in the app is:
```
2023-11-01 21:39:51.574	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
file not in PDF format or corrupted
---END ERROR---
```

But i think i should open a new issue for this problem and discuss everything there.
