### ISSUE TITLE
Fails to edit document (removed a tag)

### ISSUE THREAD

**Issue by stv0g** [astubenbord/paperless-mobile#317]
This is my log

```
2023-12-04 03:37:01.844	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2023-12-04 03:37:02.123	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2023-12-04 03:37:23.279	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
Instance of 'PaperlessFormValidationException'
---END ERROR---
---BEGIN STACKTRACE---
#0      PaperlessDocumentsApiImpl.update (package:paperless_api/src/modules/documents_api/paperless_documents_api_impl.dart:85)
<asynchronous suspension>
#1      DocumentEditCubit.updateDocument (package:paperless_mobile/features/document_edit/cubit/document_edit_cubit.dart:35)
<asynchronous suspension>
#2      _DocumentEditPageState._onSubmit (package:paperless_mobile/features/document_edit/view/document_edit_page.dart:389)
<asynchronous suspension>

---END STACKTRACE---
2023-12-04 03:37:31.845	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2023-12-04 03:37:32.144	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
> 
```

I am running Paperless-ngx 2.0.1

**Comment by astubenbord** [comment]
I see. It seems like there is an unhanded validation error (I suppose it might have to do with new fields which are not set in the app). Do you use custom fields on this document?

**Comment by beyercenter** [comment]
Same issue since paperless 2.0.0 Update...

App also shows paperless Version 0.0.0 apiv3

**Comment by astubenbord** [comment]
Yes, I did not yet get to implement support for 2.0.x and it will probably take a while because I'm quite busy at the moment. Also, the 0.0.0 version is the version coming from the server, I reported it to the team and it will be fixed in the next release.

**Comment by justb81** [comment]
This is a duplicate to #316

**Comment by astubenbord** [comment]
Thanks for noticing, I'll close this in favor of #316
