### ISSUE TITLE
[Bug]: Stuck at home screen

### ISSUE THREAD

**Issue by 94bb494nd41f** [astubenbord/paperless-mobile#318]
### What happened?

After logging in it is not possible to move from the start screen. It is however possible to move to the settings. This only occours on the Pixel 6A with Android 14

### Steps to reproduce

log in

### Log output from the app

```shell
2023-12-04 17:55:20.753	DEBUG   --- [      AuthenticationCubit] - login                    : User M***e@19***62 successfully logged in.
2023-12-04 17:55:20.881	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
type 'int' is not a subtype of type 'List<dynamic>?' in type cast
---END ERROR---
---BEGIN STACKTRACE---
#0      new PaperlessServerStatisticsModel.fromJson (package:paperless_api/src/models/paperless_server_statistics_model.dart:17)
#1      PaperlessServerStatsApiImpl.getServerStatistics (package:paperless_api/src/modules/server_stats_api/paperless_server_stats_api_impl.dart:50)
<asynchronous suspension>

---END STACKTRACE---
2023-12-04 17:55:20.901	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
Instance of 'PaperlessUnauthorizedException'
---END ERROR---
---BEGIN STACKTRACE---
#0      PaperlessDocumentsApiImpl.findAll (package:paperless_api/src/modules/documents_api/paperless_documents_api_impl.dart:111)
<asynchronous suspension>
#1      DocumentPagingBlocMixin.updateFilter (package:paperless_mobile/features/paged_document_view/cubit/document_paging_bloc_mixin.dart:89)
<asynchronous suspension>

---END STACKTRACE---
2023-12-04 17:57:52.173	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2023-12-04 17:57:52.174	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
2023-12-04 17:57:52.175	INFO    --- [                         ] -                          : Setting refresh rate to 60.0
2023-12-04 17:57:52.293	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
2023-12-04 17:57:52.293	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
2023-12-04 17:57:52.293	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
2023-12-04 17:57:52.326	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
2023-12-04 17:57:52.326	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2023-12-04 17:57:52.381	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2023-12-04 17:57:52.382	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
2023-12-04 17:57:52.486	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
2023-12-04 17:57:52.486	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
2023-12-04 17:57:52.487	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
2023-12-04 17:57:52.593	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
Instance of 'PaperlessUnauthorizedException'
---END ERROR---
---BEGIN STACKTRACE---
#0      PaperlessDocumentsApiImpl.findAll (package:paperless_api/src/modules/documents_api/paperless_documents_api_impl.dart:111)
<asynchronous suspension>
#1      DocumentPagingBlocMixin.updateFilter (package:paperless_mobile/features/paged_document_view/cubit/document_paging_bloc_mixin.dart:89)
<asynchronous suspension>

---END STACKTRACE---
2023-12-04 17:57:52.600	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
type 'int' is not a subtype of type 'List<dynamic>?' in type cast
---END ERROR---
---BEGIN STACKTRACE---
#0      new PaperlessServerStatisticsModel.fromJson (package:paperless_api/src/models/paperless_server_statistics_model.dart:17)
#1      PaperlessServerStatsApiImpl.getServerStatistics (package:paperless_api/src/modules/server_stats_api/paperless_server_stats_api_impl.dart:50)
<asynchronous suspension>

---END STACKTRACE---
2023-12-04 17:58:15.591	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2023-12-04 17:58:15.592	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
2023-12-04 17:58:15.593	INFO    --- [                         ] -                          : Setting refresh rate to 60.0
2023-12-04 17:58:15.726	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
2023-12-04 17:58:15.726	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
2023-12-04 17:58:15.726	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
2023-12-04 17:58:15.756	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
2023-12-04 17:58:15.757	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2023-12-04 17:58:15.822	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2023-12-04 17:58:15.822	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
2023-12-04 17:58:15.944	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
2023-12-04 17:58:15.944	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
2023-12-04 17:58:15.946	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
2023-12-04 17:58:16.081	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
Instance of 'PaperlessUnauthorizedException'
---END ERROR---
---BEGIN STACKTRACE---
#0      PaperlessDocumentsApiImpl.findAll (package:paperless_api/src/modules/documents_api/paperless_documents_api_impl.dart:111)
<asynchronous suspension>
#1      DocumentPagingBlocMixin.updateFilter (package:paperless_mobile/features/paged_document_view/cubit/document_paging_bloc_mixin.dart:89)
<asynchronous suspension>

---END STACKTRACE---
2023-12-04 17:58:16.088	ERROR   --- [                         ] - main                     : An unexpected error occurred
---BEGIN ERROR---
type 'int' is not a subtype of type 'List<dynamic>?' in type cast
---END ERROR---
---BEGIN STACKTRACE---
#0      new PaperlessServerStatisticsModel.fromJson (package:paperless_api/src/models/paperless_server_statistics_model.dart:17)
#1      PaperlessServerStatsApiImpl.getServerStatistics (package:paperless_api/src/modules/server_stats_api/paperless_server_stats_api_impl.dart:50)
<asynchronous suspension>

---END STACKTRACE---
```

### Paperless-ng*x Version

1.17.4

### Paperless-Mobile Version

3.1.3+57

### Device

Google Pixel 6A

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

German

**Comment by astubenbord** [comment]
Please make sure you're on the latest version (currently 3.1.3). Then try again and if it still occurs you can report back. Thanks.

**Comment by 94bb494nd41f** [comment]
I am sorry, it was already the newest version. I corrected my issue
