### ISSUE TITLE
[Bug]: Platform Exception when trying to open .md file

### ISSUE THREAD

**Issue by saket1999** [astubenbord/paperless-mobile#333]
### What happened?

Whenever I try to open markdown file, the app gives platform exception. Added the exception.

### Steps to reproduce

Open any markdown file. You will see the exception

### Log output from the app

```shell
PlatformException(c, c4.c: Can't open file, Cause: null,
Stacktrace: c4.c: Can't open file
at c4.a.d(Unknown Source:78)
at i2.m.b(Unknown Source:21)
at i2.b.a(Unknown Source:2)
at c3.a$b.a(Unknown Source:17)
at p2.c.l(Unknown Source:18)
at p2.c.m(Unknown Source:40)
at p2.c.i(Unknown Source:0)
at p2.b.run(Unknown Source:12)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:233)
at android.app.ActivityThread.main(ActivityThread.java:8068)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.r un(Runtimelnit.java:631)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978) , null)
```

### Paperless-ng*x Version

2.1.3

### Paperless-Mobile Version

3.1.8

### Device

OnePlus 6t

### Operating System Version

Android 11

### Device Locale

English

### Selected Locale

None

**Comment by astubenbord** [comment]
Are you trying to open the file inside the app (i.e. in app preview) or are you trying to open it via a system viewer?
