### ISSUE TITLE
[Bug]: PDF werden nicht angezeigt

### ISSUE THREAD

**Issue by Marzus1972** [astubenbord/paperless-mobile#362]
### What happened?

Nach der Vorschau wählt mal oben in der App das PDF aus. Dieses wir nicht angezeigt

### Steps to reproduce

Login
Auswahl des Dokumentes
Ansicht PDF im oberen Bereich

### Log output from the app

```shell
2024-01-11 11:45:15.508	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-01-11 11:45:15.510	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
2024-01-11 11:45:15.513	INFO    --- [                         ] -                          : Setting refresh rate to 120.00000762939453
2024-01-11 11:45:15.787	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
2024-01-11 11:45:15.787	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
2024-01-11 11:45:15.787	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
2024-01-11 11:45:15.826	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
2024-01-11 11:45:15.826	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2024-01-11 11:45:15.893	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2024-01-11 11:45:15.893	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
2024-01-11 11:45:16.094	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
2024-01-11 11:45:16.094	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
2024-01-11 11:45:16.095	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
2024-01-11 11:45:16.108	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-11 11:45:16.109	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 11:45:16.343	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-11 11:45:16.557	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 11:45:16.557	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-11 11:45:16.642	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-11 11:55:01.564	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 11:55:01.694	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 11:55:31.568	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 11:55:31.666	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 11:56:01.592	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 11:56:01.693	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 11:56:31.570	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 11:56:31.669	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 11:57:01.591	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 11:57:01.706	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 21:03:16.246	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-11 21:03:16.476	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-11 21:03:46.241	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 21:03:46.333	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 21:04:16.241	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 21:04:16.309	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 21:04:46.241	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 21:04:46.339	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 21:13:27.295	INFO    --- [        DocumentEditCubit] - loadFieldSuggestions     : Loading suggestions for document 57...
2024-01-11 21:13:27.632	INFO    --- [        DocumentEditCubit] - loadFieldSuggestions     : Found 1 suggestions for document 57.
2024-01-11 21:13:30.062	INFO    --- [        DocumentEditCubit] - loadFieldSuggestions     : Loading suggestions for document 57...
2024-01-11 21:13:30.378	INFO    --- [        DocumentEditCubit] - loadFieldSuggestions     : Found 1 suggestions for document 57.
2024-01-11 21:13:37.587	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 21:13:37.680	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 21:13:45.923	DEBUG   --- [      AuthenticationCubit] - logout                   : Logging out marcus.koenig@19***10...
2024-01-11 21:13:45.923	DEBUG   --- [      AuthenticationCubit] - _resetExternalState      : Resetting security context...
2024-01-11 21:13:45.923	DEBUG   --- [      AuthenticationCubit] - _resetExternalState      : Security context reset.
2024-01-11 21:13:45.923	DEBUG   --- [      AuthenticationCubit] - _resetExternalState      : Clearing local state...
2024-01-11 21:13:45.932	DEBUG   --- [      AuthenticationCubit] - _resetExternalState      : Local state cleard.
2024-01-11 21:13:45.932	DEBUG   --- [      AuthenticationCubit] - removeAccount            : Trying to remove account marcus.koenig@19***10...
2024-01-11 21:13:45.932	DEBUG   --- [              FileService] - clearUserData            : Clearing data for user marcus.koenig@19***10...
2024-01-11 21:13:45.965	TRACE   --- [              FileService] - clearUserData            : Clearing scans directory...
2024-01-11 21:13:45.965	TRACE   --- [              FileService] - clearUserData            : Removed 0 B...
2024-01-11 21:13:45.965	TRACE   --- [              FileService] - clearUserData            : Removing temporary files and cache content...
2024-01-11 21:13:45.970	TRACE   --- [              FileService] - clearUserData            : Removed 12.48 MB...
2024-01-11 21:13:45.970	TRACE   --- [              FileService] - clearUserData            : Removing files waiting for consumption...
2024-01-11 21:13:45.970	TRACE   --- [              FileService] - clearUserData            : Removed 0 B...
2024-01-11 21:13:46.273	DEBUG   --- [      AuthenticationCubit] - logout                   : User successfully logged out.
2024-01-11 21:14:08.493	DEBUG   --- [      AuthenticationCubit] - login                    : Trying to log in Marcus@19***10...
2024-01-11 21:14:08.493	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Adding new user Marcus@19***10..
2024-01-11 21:14:08.493	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Fetching bearer token from the server...
2024-01-11 21:14:09.058	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Bearer token successfully retrieved.
2024-01-11 21:14:09.060	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2024-01-11 21:14:09.096	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2024-01-11 21:14:09.096	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Trying to fetch remote paperless user for Marcus@19***10.
2024-01-11 21:14:09.190	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Remote paperless user successfully fetched.
2024-01-11 21:14:09.191	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Persisting user account information...
2024-01-11 21:14:09.205	DEBUG   --- [      AuthenticationCubit] - _addUser                 : User account information successfully persisted.
2024-01-11 21:14:09.205	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Persisting user app state...
2024-01-11 21:14:09.207	DEBUG   --- [      AuthenticationCubit] - _addUser                 : User state successfully persisted.
2024-01-11 21:14:09.409	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Saving user credentials inside encrypted storage...
2024-01-11 21:14:09.410	DEBUG   --- [      AuthenticationCubit] - _addUser                 : User credentials successfully saved.
2024-01-11 21:14:09.411	DEBUG   --- [      AuthenticationCubit] - login                    : User Marcus@19***10 successfully logged in.
2024-01-11 21:14:09.421	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-11 21:14:09.422	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 21:14:09.649	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-11 21:14:09.733	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 21:14:09.733	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-11 21:14:09.812	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-11 21:14:36.821	DEBUG   --- [      AuthenticationCubit] - logout                   : Logging out Marcus@19***10...
2024-01-11 21:14:36.821	DEBUG   --- [      AuthenticationCubit] - _resetExternalState      : Resetting security context...
2024-01-11 21:14:36.821	DEBUG   --- [      AuthenticationCubit] - _resetExternalState      : Security context reset.
2024-01-11 21:14:36.821	DEBUG   --- [      AuthenticationCubit] - _resetExternalState      : Clearing local state...
2024-01-11 21:14:36.822	DEBUG   --- [      AuthenticationCubit] - _resetExternalState      : Local state cleard.
2024-01-11 21:14:36.822	DEBUG   --- [      AuthenticationCubit] - removeAccount            : Trying to remove account Marcus@19***10...
2024-01-11 21:14:36.822	DEBUG   --- [              FileService] - clearUserData            : Clearing data for user Marcus@19***10...
2024-01-11 21:14:36.835	ERROR   --- [                         ] - main                     : An unexpected error occurred 
---BEGIN ERROR---
PathNotFoundException: Directory listing failed, path = '/data/user/0/de.astubenbord.paperless_mobile/cache/scans/' (OS Error: No such file or directory, errno = 2)
---END ERROR---
---BEGIN STACKTRACE---

---END STACKTRACE---
2024-01-11 21:15:05.949	ERROR   --- [                         ] - main                     : An unexpected error occurred 
---BEGIN ERROR---
Bad state: No element
---END ERROR---
---BEGIN STACKTRACE---
#0      List.first (dart:core-patch/growable_array.dart:343)
#1      FormBuilderState.validate (package:flutter_form_builder/src/form_builder.dart:260)
#2      FormBuilderState.saveAndValidate (package:flutter_form_builder/src/form_builder.dart:286)
#3      _AddAccountPageState._onSubmit (package:paperless_mobile/features/login/view/add_account_page.dart:384)
#4      _AddAccountPageState.build.<anonymous closure> (package:paperless_mobile/features/login/view/add_account_page.dart:190)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#23     _rootRunUnary (dart:async/zone.dart:1415)
#24     _CustomZone.runUnary (dart:async/zone.dart:1308)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#26     _invoke1 (dart:ui/hooks.dart:330)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)

---END STACKTRACE---
2024-01-11 21:15:16.606	DEBUG   --- [      AuthenticationCubit] - login                    : Trying to log in Marcus @19***10...
2024-01-11 21:15:16.606	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Adding new user Marcus @19***10..
2024-01-11 21:15:16.607	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Fetching bearer token from the server...
2024-01-11 21:16:31.601	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-01-11 21:16:31.602	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
2024-01-11 21:16:31.607	INFO    --- [                         ] -                          : Setting refresh rate to 120.00000762939453
2024-01-11 21:16:31.833	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
2024-01-11 21:16:31.834	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
2024-01-11 21:16:31.834	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
2024-01-11 21:16:31.861	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
2024-01-11 21:16:31.861	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2024-01-11 21:16:31.889	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2024-01-11 21:16:31.890	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
2024-01-11 21:16:31.957	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
2024-01-11 21:16:31.957	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
2024-01-11 21:16:31.958	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
2024-01-11 21:16:31.967	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-11 21:16:31.967	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 21:16:32.584	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 21:16:32.584	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-11 21:16:32.584	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-11 21:16:32.649	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-11 21:17:41.725	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 21:17:41.811	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
```

### Screenshots

![Screenshot_20240111_211709](https://github.com/astubenbord/paperless-mobile/assets/156366963/ce0474a1-b2bc-4ca6-92a7-bf5ffa32f4bc)
![Screenshot_20240111_211659](https://github.com/astubenbord/paperless-mobile/assets/156366963/55590d55-2475-4860-a889-db730ca93706)

### Paperless-ng*x Version

2.1.3 APIv3

### Paperless-Mobile Version

3.2.0-404

### Device

Samsung Gal s21 ultra

### Operating System Version

14

### Device Locale

German

### Selected Locale

None

**Comment by l0wskilled** [comment]
Kann ich bestätigen. Nginx Access Log sagt 200 beim Download Request

**Comment by astubenbord** [comment]
Ja, ist mir bekannt, der Bug wurde bereits mehrfach reported. Ich schließe das Ticket als abgeschlossen und als Duplikat von #350. 

Es gibt momentan ein Problem in der Build Pipeline das ich erst beheben muss. Da ich aber aktuell ziemlich beschäftigt bin kann sich das noch ein paar Tage ziehen, sorry.
