### ISSUE TITLE
[Bug]: Failure to re-login due to locale unsupported

### ISSUE THREAD

**Issue by barndoor101** [astubenbord/paperless-mobile#375]
### What happened?

I have a paperless-ngx instance running as an LXC on proxmox, using nginx proxy manager to give it a public url.
When I log into that using the app it works perfectly the first time, on subsequent loads (even after restarting the app) it gets stuck 'Restoring session' with an error of 'S.delegate failed to load unsupported locale "en_GB". This is likely an issue with the localizations generation tool."

### Steps to reproduce

1. Login to paperless-ngx once
2. Close app
3. Open app again

### Paperless-ng*x Version

2.4.0

### Paperless-Mobile Version

3.2.1

### Device

Moto G 5G

### Operating System Version

Android 11

### Device Locale

en_GB

### Selected Locale

None

**Comment by tomc128** [comment]
Also getting this error. Here's the error logs for mine if at all useful.

```
2024-01-31 11:13:48.841	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-01-31 11:13:48.841	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Verifying user identity...
2024-01-31 11:13:48.842	ERROR   --- [                         ] - main                     : An unexpected error occurred 
---BEGIN ERROR---
S.delegate failed to load unsupported locale "en_GB". This is likely an issue with the localizations generation tool. Please file an issue on GitHub with a reproducible sample app and the gen-l10n configuration that was used.
---END ERROR---
---BEGIN STACKTRACE---
#0      lookupS (package:paperless_mobile/generated/l10n/app_localizations.dart:2566)
#1      _SDelegate.load (package:paperless_mobile/generated/l10n/app_localizations.dart:2537)
#2      AuthenticationCubit.restoreSession (package:paperless_mobile/features/login/cubit/authentication_cubit.dart:283)
#3      _GoRouterShellState.initState.<anonymous closure> (package:paperless_mobile/main.dart:272)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:978)
#7      _rootRun (dart:async/zone.dart:1391)
#8      _CustomZone.run (dart:async/zone.dart:1301)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1209)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#11     _rootRun (dart:async/zone.dart:1399)
#12     _CustomZone.run (dart:async/zone.dart:1301)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233)
#14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

---END STACKTRACE---
2024-01-31 11:13:48.843	INFO    --- [                         ] -                          : Setting refresh rate to 120.00000762939453
```

**Comment by barndoor101** [comment]
So I think I've sorted it - you have to specifically set your language and locale on the server side, not use the default, otherwise it falls over. Still worth looking at as most people won't specifically set their locale web side.

**Comment by astubenbord** [comment]
You're right. Might have to do with the accept-locale header? I'll look into this once I have more time.

**Comment by 10tec-eth** [comment]
> So I think I've sorted it - you have to specifically set your language and locale on the server side, not use the default, otherwise it falls over. Still worth looking at as most people won't specifically set their locale web side.

Could you give a little more info on where you changed the locale to fix this issue? I've set both the Display Language and Date Display to English (GB) in the settings but still have the error.

I'm on Unraid if that helps anything...!

My error logs:

2024-05-13 19:20:33.542	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-05-13 19:20:33.542	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Verifying user identity...
2024-05-13 19:20:33.543	ERROR   --- [                         ] - main                     : An unexpected error occurred 
---BEGIN ERROR---
S.delegate failed to load unsupported locale "en_GB". This is likely an issue with the localizations generation tool. Please file an issue on GitHub with a reproducible sample app and the gen-l10n configuration that was used.
---END ERROR---
---BEGIN STACKTRACE---
#0      lookupS (package:paperless_mobile/generated/l10n/app_localizations.dart:2566)
#1      _SDelegate.load (package:paperless_mobile/generated/l10n/app_localizations.dart:2537)
#2      AuthenticationCubit.restoreSession (package:paperless_mobile/features/login/cubit/authentication_cubit.dart:283)
#3      _GoRouterShellState.initState.<anonymous closure> (package:paperless_mobile/main.dart:272)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:978)
#7      _rootRun (dart:async/zone.dart:1391)
#8      _CustomZone.run (dart:async/zone.dart:1301)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1209)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#11     _rootRun (dart:async/zone.dart:1399)
#12     _CustomZone.run (dart:async/zone.dart:1301)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233)
#14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

---END STACKTRACE---
2024-05-13 19:20:33.545	INFO    --- [                         ] -                          : Setting refresh rate to 120.00000762939453

**Comment by 10tec-eth** [comment]
> You're right. Might have to do with the accept-locale header? I'll look into this once I have more time.

Hi mate, did you get a chance to look in to this one by chance?

**Comment by barndoor101** [comment]
> > So I think I've sorted it - you have to specifically set your language and locale on the server side, not use the default, otherwise it falls over. Still worth looking at as most people won't specifically set their locale web side.
> 
> Could you give a little more info on where you changed the locale to fix this issue? I've set both the Display Language and Date Display to English (GB) in the settings but still have the error.
> 
> I'm on Unraid if that helps anything...!
> 
> My error logs:
> 
> 2024-05-13 19:20:33.542 DEBUG --- [ AuthenticationCubit] - restoreSession : Trying to restore previous session... 2024-05-13 19:20:33.542 DEBUG --- [ AuthenticationCubit] - restoreSession : Verifying user identity... 2024-05-13 19:20:33.543 ERROR --- [ ] - main : An unexpected error occurred ---BEGIN ERROR--- S.delegate failed to load unsupported locale "en_GB". This is likely an issue with the localizations generation tool. Please file an issue on GitHub with a reproducible sample app and the gen-l10n configuration that was used. ---END ERROR--- ---BEGIN STACKTRACE--- #0 lookupS (package:paperless_mobile/generated/l10n/app_localizations.dart:2566) #1 _SDelegate.load (package:paperless_mobile/generated/l10n/app_localizations.dart:2537) #2 AuthenticationCubit.restoreSession (package:paperless_mobile/features/login/cubit/authentication_cubit.dart:283) #3 _GoRouterShellState.initState. (package:paperless_mobile/main.dart:272) #4 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325) #5 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264) #6 SchedulerBinding.scheduleWarmUpFrame. (package:flutter/src/scheduler/binding.dart:978) #7 _rootRun (dart:async/zone.dart:1391) #8 _CustomZone.run (dart:async/zone.dart:1301) #9 _CustomZone.runGuarded (dart:async/zone.dart:1209) #10 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:1249) #11 _rootRun (dart:async/zone.dart:1399) #12 _CustomZone.run (dart:async/zone.dart:1301) #13 _CustomZone.bindCallback. (dart:async/zone.dart:1233) #14 Timer._createTimer. (dart:async-patch/timer_patch.dart:18) #15 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398) #16 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429) #17 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
> 
> ---END STACKTRACE--- 2024-05-13 19:20:33.545 INFO --- [ ] - : Setting refresh rate to 120.00000762939453

It was those 2, but in terms of order of events, I logged in initially - it was fine, then it failed to relogin. Thats when I cahnged it server side.

**Comment by 10tec-eth** [comment]
> > > So I think I've sorted it - you have to specifically set your language and locale on the server side, not use the default, otherwise it falls over. Still worth looking at as most people won't specifically set their locale web side.
> > 
> > Could you give a little more info on where you changed the locale to fix this issue? I've set both the Display Language and Date Display to English (GB) in the settings but still have the error.
> > 
> > I'm on Unraid if that helps anything...!
> > 
> > My error logs:
> > 
> 
> It was those 2, but in terms of order of events, I logged in initially - it was fine, then it failed to relogin. Thats when I cahnged it server side.

Thanks mate. Yes, that's exactly my scenario as well, however your solution didn't hasn't resolved my issue. It worked great for the first login, then failed.

Restarting the container with the new settings applied hasn't worked either.

Thanks for your response!

**Comment by t34wrj** [comment]
I also have this same issue. Please let me know if logs would be helpful.

**Comment by bingobob** [comment]
Hi all - i have this error message when trying to download from the android app (which is otherwise brilliant).

running Paperless-ngx LXC latest on proxmox.. 

any tips how to fix please ?

**Comment by MaximumFish** [comment]
Just had the same issue. As barndoor101 said, go to your Paperless-ngx settings (on the web, not in the app) and set both the display language and date display to English (GB). Remeber to save the changes, and a restart of the container can't hurt.

Next you'll need to clear the storage for Paperless Mobile (or uninstall/reinstall the app) and set it back up from scratch. This time when you change the app language it should work properly.

**Comment by bingobob** [comment]
Tank you so much, just did the fix proposed and working great!
