### ISSUE TITLE
[Bug]: doesn't start (HiveError: Cannot read, unknown typeId: 132. Did you forget to register an adapter?)

### ISSUE THREAD

**Issue by eliasp** [astubenbord/paperless-mobile#389]
### What happened?

The app doesn't start anymore since quite some time. It just shows the splash screen.

### Steps to reproduce

1. Start the App
2. Wait…

### Log output from the app

```shell
02-23 23:04:27.872 21603 12544 I flutter : Logging files to /storage/emulated/0/Android/data/de.astubenbord.paperless_mobile/files/documents/logs/2024-02-23.log.
02-23 23:04:27.889 21603 12544 I flutter : 2024-02-23 23:04:27.889      ERROR   --- [                         ] - main                     : An unexpected error occurred 
02-23 23:04:27.890 21603 12544 I flutter : ---BEGIN ERROR---
02-23 23:04:27.890 21603 12544 I flutter : HiveError: Cannot read, unknown typeId: 132. Did you forget to register an adapter?
02-23 23:04:27.892 21603 12544 I flutter : ---END ERROR---
02-23 23:04:27.892 21603 12544 I flutter : ---BEGIN STACKTRACE---
02-23 23:04:27.893 21603 12544 I flutter : #0      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:325)
02-23 23:04:27.893 21603 12544 I flutter : #1      LocalUserAppStateAdapter.read (package:paperless_mobile/core/database/tables/local_user_app_state.g.dart:17)
02-23 23:04:27.893 21603 12544 I flutter : #2      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:328)
02-23 23:04:27.893 21603 12544 I flutter : #3      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:276)
02-23 23:04:27.893 21603 12544 I flutter : #4      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
02-23 23:04:27.893 21603 12544 I flutter : #5      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
02-23 23:04:27.893 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.893 21603 12544 I flutter : #6      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
02-23 23:04:27.893 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.893 21603 12544 I flutter : #7      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
02-23 23:04:27.893 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.893 21603 12544 I flutter : #8      HiveImpl.openBox (package:hive/src/hive_impl.dart:142)
02-23 23:04:27.893 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.893 21603 12544 I flutter : #9      initHive (package:paperless_mobile/core/database/hive/hive_initialization.dart:14)
02-23 23:04:27.893 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.893 21603 12544 I flutter : #10     main.<anonymous closure> (package:paperless_mobile/main.dart:138)
02-23 23:04:27.893 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.893 21603 12544 I flutter : 
02-23 23:04:27.893 21603 12544 I flutter : ---END STACKTRACE---
02-23 23:04:27.893 21603 12544 I flutter : 2024-02-23 23:04:27.889      ERROR   --- [                         ] - main                     : An unexpected error occurred 
02-23 23:04:27.894 21603 12544 I flutter : ---BEGIN ERROR---
02-23 23:04:27.894 21603 12544 I flutter : HiveError: Cannot read, unknown typeId: 132. Did you forget to register an adapter?
02-23 23:04:27.895 21603 12544 I flutter : ---END ERROR---
02-23 23:04:27.895 21603 12544 I flutter : ---BEGIN STACKTRACE---
02-23 23:04:27.895 21603 12544 I flutter : #0      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:325)
02-23 23:04:27.895 21603 12544 I flutter : #1      LocalUserAppStateAdapter.read (package:paperless_mobile/core/database/tables/local_user_app_state.g.dart:17)
02-23 23:04:27.895 21603 12544 I flutter : #2      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:328)
02-23 23:04:27.895 21603 12544 I flutter : #3      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:276)
02-23 23:04:27.895 21603 12544 I flutter : #4      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
02-23 23:04:27.895 21603 12544 I flutter : #5      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
02-23 23:04:27.895 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.895 21603 12544 I flutter : #6      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
02-23 23:04:27.895 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.895 21603 12544 I flutter : #7      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
02-23 23:04:27.895 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.895 21603 12544 I flutter : #8      HiveImpl.openBox (package:hive/src/hive_impl.dart:142)
02-23 23:04:27.895 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.895 21603 12544 I flutter : #9      initHive (package:paperless_mobile/core/database/hive/hive_initialization.dart:14)
02-23 23:04:27.895 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.895 21603 12544 I flutter : #10     main.<anonymous closure> (package:paperless_mobile/main.dart:138)
02-23 23:04:27.895 21603 12544 I flutter : <asynchronous suspension>
02-23 23:04:27.895 21603 12544 I flutter : 
02-23 23:04:27.896 21603 12544 I flutter : ---END STACKTRACE---
```

### Paperless-ng*x Version

2.5.2

### Paperless-Mobile Version

3.2.1

### Device

OnePlus Nord (AC2003)

### Operating System Version

Android 11

### Device Locale

english

### Selected Locale

English (US)

**Comment by eliasp** [comment]
Closing this, since this most likely happened due to version incompatibilities after upgrading, without resetting the App's state (which is not supported yet).
