### ISSUE TITLE
[Bug]:  Cannot upload Scans Error.

### ISSUE THREAD

**Issue by reacend** [astubenbord/paperless-mobile#392]
### What happened?

When I scan an Paper witht he app and upload it, i get this error.:

![Screenshot_20240229_121928](https://github.com/astubenbord/paperless-mobile/assets/106918432/ecad3445-e2a7-4577-95c0-1e261fab83fe)

### Steps to reproduce

normal upload of pdf works only the scan app did not work
Changed the upload to pdf no help.

### Log output from the app

```shell
See Screenshot
```

### Paperless-ng*x Version

2.5.4

### Paperless-Mobile Version

play store version

### Device

samsung s22 ultra

### Operating System Version

android 13

### Device Locale

germand

### Selected Locale

German

**Comment by mrsumanbiswas** [comment]
It sounds like there might be a permission error. Let's ensure that both the document and the user have full permissions. Try granting all permissions to the document for the user, and also granting all permissions to the user.

**Comment by mrsumanbiswas** [comment]
![Screenshot_20240229_172920_Kiwi Browser](https://github.com/astubenbord/paperless-mobile/assets/89653112/455cd8f2-d8f3-4548-997f-92d65e134948)
![Screenshot_20240229_172936_Kiwi Browser](https://github.com/astubenbord/paperless-mobile/assets/89653112/5a52e6f6-aa77-4129-a071-efe90bcdb29c)

**Comment by reacend** [comment]
The user of papermobile is superuser.

**Comment by mrsumanbiswas** [comment]
![Screenshot_20240229_174621](https://github.com/astubenbord/paperless-mobile/assets/89653112/b8c44fa3-71e4-4e45-a816-d11a68a6b9ec)


**Please attempt to switch on/off the "Upload scans as PDF" option.**

**Comment by reacend** [comment]
already testet it no success. one time i get an upload of an image only.

**Comment by mrsumanbiswas** [comment]
Mine is working fine.

**Comment by reacend** [comment]
great xD

**Comment by reacend** [comment]
still there the problem

Imagemagick was not probertly configured-

With this comment:
https://github.com/paperless-ngx/paperless-ngx/issues/895#issuecomment-1471765429

**Comment by reacend** [comment]
an 2 pages upload will work only in jpeg format it is not possible.

**Comment by reacend** [comment]
*push* any fixes?

**Comment by astubenbord** [comment]
Sorry for the late reply, I currently have hardly any time to work on the project or fix bugs. I'll look into this as soon as I have more spare time again.

**Comment by pappou99** [comment]
I have the same problem.

With the switch "Upload scans as PDF" on or off it is:
```2024-09-23 17:46:32.403	ERROR   --- [                         ] - main                     : An unexpected error occurred 
---BEGIN ERROR---
PathNotFoundException: Cannot open file, path = '/data/user/0/de.astubenbord.paperless_mobile/cache/scans/8fd9a790-37c4-1161-a471-adb3e84a1bd2.jpeg' (OS Error: No such file or directory, errno = 2)
---END ERROR---
---BEGIN STACKTRACE---
#0      _File.throwIfError (dart:io/file_impl.dart:675)
#1      _File.openSync (dart:io/file_impl.dart:490)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574)
#3      _ScannerPageState._assembleFileBytes (package:paperless_mobile/features/document_scan/view/scanner_page.dart:400)
#4      _ScannerPageState._onPrepareDocumentUpload (package:paperless_mobile/features/document_scan/view/scanner_page.dart:254)
#5      _ScannerPageState._buildActions.<anonymous closure>.<anonymous closure> (package:paperless_mobile/features/document_scan/view/scanner_page.dart:163)
#6      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#19     _rootRunUnary (dart:async/zone.dart:1415)
#20     _CustomZone.runUnary (dart:async/zone.dart:1308)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#22     _invoke1 (dart:ui/hooks.dart:330)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)

---END STACKTRACE---```

Android 8.1.0 Googlefree on Shift 6m

**Comment by lilveg** [comment]
Are you using a reverse proxy? This looks exactly like #502

**Comment by reacend** [comment]
hi,
this config of nginx fixed the issue:




location /paperless {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_pass       http://127.0.0.1:8010;
    # Websockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_redirect off;
    client_max_body_size 50M;   ### <- This helps us!
    proxy_set_header X-Forwarded-Host $server_name;
  }

**Comment by reacend** [comment]
fixed
