### ISSUE TITLE
[Bug]: Remove of scanned pages did not work

### ISSUE THREAD

**Issue by timomatrixer** [astubenbord/paperless-mobile#395]
### What happened?

Removing page after shoot one under scanner tab did not work

### Steps to reproduce

1. Scanner
2. Camera symbol
3. Shoot one site
4. Try to remove the page

### Screenshots

![Screenshot_20240307-061029](https://github.com/astubenbord/paperless-mobile/assets/40664333/a37d78c0-cd01-4138-9633-0b7f22d46712)

### Paperless-ng*x Version

2.5.4

### Paperless-Mobile Version

3.2.1+405

### Device

Pixel 7 Pro

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

None

### Additional Context

[paperless_mobile_logs_2024-04-08.log](https://github.com/astubenbord/paperless-mobile/files/14903792/paperless_mobile_logs_2024-04-08.log)

**Comment by astubenbord** [comment]
Could you please add the logs to the issue? Thanks.

**Comment by timomatrixer** [comment]
> Could you please add the logs to the issue? Thanks.

Done

**Comment by GregSutcliffe** [comment]
I've seen this issue and can provide logs:

```
2024-04-08 10:38:43.513 ERROR   --- [                         ] - main                     : An unexpected error occurred 
---BEGIN ERROR---
PathNotFoundException: Cannot open file, path = '/data/user/0/de.astubenbord.paperless_mobile/cache/scans/ea90e4e0-cab6-1f5c-a84b-d78ac31cb058.jpeg' (OS Error: No such file or directory, errno = 2)
---END ERROR---
---BEGIN STACKTRACE---
#0      _File.throwIfError (dart:io/file_impl.dart:675)
#1      _File.openSync (dart:io/file_impl.dart:490)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574)
#3      _ScannerPageState._assembleFileBytes (package:paperless_mobile/features/document_scan/view/scanner_page.dart:400)
#4      _ScannerPageState._onPrepareDocumentUpload (package:paperless_mobile/features/document_scan/view/scanner_page.dart:254)
#5      _ScannerPageState._buildActions.<anonymous closure>.<anonymous closure> (package:paperless_mobile/features/document_scan/view/scanner_page.dart:163)
#6      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#19     _rootRunUnary (dart:async/zone.dart:1415)
#20     _CustomZone.runUnary (dart:async/zone.dart:1308)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#22     _invoke1 (dart:ui/hooks.dart:330)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
```
