### ISSUE TITLE
[Bug]: Settings page only shows Appearance header with gray box

### ISSUE THREAD

**Issue by alex3305** [astubenbord/paperless-mobile#403]
### What happened?

When I open the Settings page, I only get a blank (grey) screen (see screenshots below).

### Steps to reproduce

1. Login on my Paperless NGX instance
2. Open the app
3. Go to settings

### Log output from the app

```shell
03-21 10:56:12.919  8759  8759 I SurfaceView@5836b37: onWindowVisibilityChanged(0) true io.flutter.embedding.android.j{5836b37 V.E...... ......I. 0,0-0,0} of ViewRootImpl@120ee35[MainActivity]
03-21 10:56:12.924  8759  8796 I flutter : Logging files to /storage/emulated/0/Android/data/de.astubenbord.paperless_mobile/files/documents/logs/2024-03-21.log.
03-21 10:56:12.933  8759  8759 I SurfaceView@5836b37: windowStopped(false) true io.flutter.embedding.android.j{5836b37 V.E...... ......ID 0,0-1080,2400} of ViewRootImpl@120ee35[MainActivity]
03-21 10:56:12.935  8759  8759 I SurfaceView@5836b37: surfaceCreated 1 #8 io.flutter.embedding.android.j{5836b37 V.E...... ......ID 0,0-1080,2400}
03-21 10:56:12.936  8759  8759 I SurfaceView@5836b37: surfaceChanged (1080,2400) 1 #8 io.flutter.embedding.android.j{5836b37 V.E...... ......ID 0,0-1080,2400}
03-21 10:56:12.967  8759  8796 I flutter : 2024-03-21 10:56:12.967      DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
03-21 10:56:12.969  8759  8796 I flutter : dynamic_color: Core palette detected.
03-21 10:56:12.971  8759  8796 I flutter : 2024-03-21 10:56:12.967      DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
03-21 10:56:12.971  8759  8796 I flutter : 2024-03-21 10:56:12.970      INFO    --- [                         ] -                          : Setting refresh rate to 120.00000762939453
03-21 10:56:13.088  8759  8796 I flutter : 2024-03-21 10:56:13.088      DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
03-21 10:56:13.089  8759  8796 I flutter : 2024-03-21 10:56:13.088      DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
03-21 10:56:13.089  8759  8796 I flutter : 2024-03-21 10:56:13.088      DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
03-21 10:56:13.206  8759  8796 I flutter : 2024-03-21 10:56:13.206      DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
03-21 10:56:13.206  8759  8796 I flutter : 2024-03-21 10:56:13.206      DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
03-21 10:56:13.270  8759  8796 I flutter : 2024-03-21 10:56:13.270      WARNING --- [      AuthenticationCubit] - _getApiVersion           : The server is running a newer API version (5) than the a
pp supports (v3), falling back to latest supported version (v3). Warning: This might lead to unexpected behavior!
03-21 10:56:13.271  8759  8796 I flutter : 2024-03-21 10:56:13.271      DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
03-21 10:56:13.271  8759  8796 I flutter : 2024-03-21 10:56:13.271      DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
03-21 10:56:13.341  8759  8796 I flutter : 2024-03-21 10:56:13.341      DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
03-21 10:56:13.341  8759  8796 I flutter : 2024-03-21 10:56:13.341      DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
03-21 10:56:13.342  8759  8796 I flutter : 2024-03-21 10:56:13.341      DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
03-21 10:56:13.346  8759  8796 I flutter : 2024-03-21 10:56:13.346      DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
03-21 10:56:13.372  8759  8796 I flutter : 2024-03-21 10:56:13.346      INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
03-21 10:56:13.549  8759  8796 I flutter : 2024-03-21 10:56:13.549      DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
03-21 10:56:13.550  8759  8796 I flutter : 2024-03-21 10:56:13.549      INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
03-21 10:56:13.550  8759  8796 I flutter : 2024-03-21 10:56:13.550      DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
03-21 10:56:13.605  8759  8796 I flutter : 2024-03-21 10:56:13.605      DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
03-21 10:56:21.765  8759  8759 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.m{bbd67b3 VFED..... .F....ID 0,0-1080,2400 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_IN
PUT
03-21 10:56:21.790  8759  8759 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.m{bbd67b3 VFED..... .F....ID 0,0-1080,2400 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_IN
PUT
03-21 10:56:25.259  8759  8796 I flutter : Null check operator used on a null value
03-21 10:56:25.262  8759  8796 I flutter : #0      _LanguageSelectionSettingState.build.<anonymous closure> (package:paperless_mobile/features/settings/view/widgets/language_selection_setting.
dart:36)
03-21 10:56:25.262  8759  8796 I flutter : #1      GlobalSettingsBuilder.build.<anonymous closure> (package:paperless_mobile/features/settings/view/widgets/global_settings_builder.dart:17)
03-21 10:56:25.262  8759  8796 I flutter : #2      _ValueListenableBuilderState.build (package:flutter/src/widgets/value_listenable_builder.dart:181)
03-21 10:56:25.262  8759  8796 I flutter : #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
03-21 10:56:25.262  8759  8796 I flutter : #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
03-21 10:56:25.262  8759  8796 I flutter : #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
03-21 10:56:25.262  8759  8796 I flutter : #6      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
03-21 10:56:25.262  8759  8796 I flutter : #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
03-21 10:56:25.262  8759  8796 I flutter : #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
03-21 10:56:25.262  8759  8796 I flutter : #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
03-21 10:56:25.262  8759  8796 I flutter : #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
03-21 10:56:25.262  8759  8796 I flutter : #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
03-21 10:56:25.262  8759  8796 I flutter : #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
03-21 10:56:25.262  8759  8796 I flutter : #13     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
03-21 10:56:25.262  8759  8796 I flutter : #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
03-21 10:56:25.262  8759  8796 I flutter : #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
03-21 10:56:25.262  8759  8796 I flutter : #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
03-21 10:56:25.262  8759  8796 I flutter : #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
03-21 10:56:25.262  8759  8796 I flutter : #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
03-21 10:56:25.262  8759  8796 I flutter : #19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
03-21 10:56:25.262  8759  8796 I flutter : #20     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
03-21 10:56:25.262  8759  8796 I flutter : #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
03-21 10:56:25.262  8759  8796 I flutter : #22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
03-21 10:56:25.262  8759  8796 I flutter : #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
03-21 10:56:25.262  8759  8796 I flutter : #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
03-21 10:56:25.262  8759  8796 I flutter : #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
03-21 10:56:25.262  8759  8796 I flutter : #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
03-21 10:56:25.262  8759  8796 I flutter : #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
03-21 10:56:25.262  8759  8796 I flutter : #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
03-21 10:56:25.262  8759  8796 I flutter : #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
03-21 10:56:25.262  8759  8796 I flutter : #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
03-21 10:56:25.262  8759  8796 I flutter : #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
03-21 10:56:25.262  8759  8796 I flutter : #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
03-21 10:56:25.262  8759  8796 I flutter : #33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
03-21 10:56:25.262  8759  8796 I flutter : #34     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
03-21 10:56:25.262  8759  8796 I flutter : #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
03-21 10:56:25.262  8759  8796 I flutter : #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
03-21 10:56:25.262  8759  8796 I flutter : #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
03-21 10:56:25.262  8759  8796 I flutter : #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
03-21 10:56:25.262  8759  8796 I flutter : #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
03-21 10:56:25.262  8759  8796 I flutter : #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
03-21 10:56:25.262  8759  8796 I flutter : #41     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
03-21 10:56:25.262  8759  8796 I flutter : #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
03-21 10:56:25.262  8759  8796 I flutter : #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
03-21 10:56:25.262  8759  8796 I flutter : #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
03-21 10:56:25.262  8759  8796 I flutter : #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
03-21 10:56:25.262  8759  8796 I flutter : #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
03-21 10:56:25.262  8759  8796 I flutter : #47     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
03-21 10:56:25.262  8759  8796 I flutter : #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
03-21 10:56:25.262  8759  8796 I flutter : #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
03-21 10:56:25.262  8759  8796 I flutter : #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
03-21 10:56:25.262  8759  8796 I flutter : #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
03-21 10:56:25.262  8759  8796 I flutter : #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
03-21 10:56:25.262  8759  8796 I flutter : #53     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
03-21 10:56:25.262  8759  8796 I flutter : #54     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
03-21 10:56:25.262  8759  8796 I flutter : #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
03-21 10:56:25.262  8759  8796 I flutter : #56     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
03-21 10:56:25.262  8759  8796 I flutter : #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
03-21 10:56:25.262  8759  8796 I flutter : #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
03-21 10:56:25.262  8759  8796 I flutter : #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
03-21 10:56:25.262  8759  8796 I flutter : #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
03-21 10:56:25.262  8759  8796 I flutter : #61     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
03-21 10:56:25.262  8759  8796 I flutter : #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
03-21 10:56:25.262  8759  8796 I flutter : #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
03-21 10:56:25.262  8759  8796 I flutter : #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
03-21 10:56:25.262  8759  8796 I flutter : #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
03-21 10:56:25.262  8759  8796 I flutter : #66     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:858)
03-21 10:56:25.262  8759  8796 I flutter : #67     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:843)
03-21 10:56:25.262  8759  8796 I flutter : #68     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835)
03-21 10:56:25.262  8759  8796 I flutter : #69     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:835)
03-21 10:56:25.263  8759  8796 I flutter : #70     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349)
03-21 10:56:25.263  8759  8796 I flutter : #71     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657)
03-21 10:56:25.263  8759  8796 I flutter : #72     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071)
03-21 10:56:25.263  8759  8796 I flutter : #73     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657)
03-21 10:56:25.263  8759  8796 I flutter : #74     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338)
03-21 10:56:25.263  8759  8796 I flutter : #75     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:486)
03-21 10:56:25.263  8759  8796 I flutter : #76     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239)
03-21 10:56:25.263  8759  8796 I flutter : #77     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:281)
03-21 10:56:25.263  8759  8796 I flutter : #78     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
03-21 10:56:25.263  8759  8796 I flutter : #79     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
03-21 10:56:25.263  8759  8796 I flutter : #80     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
03-21 10:56:25.263  8759  8796 I flutter : #81     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
03-21 10:56:25.263  8759  8796 I flutter : #82     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601)
03-21 10:56:25.263  8759  8796 I flutter : #83     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1554)
03-21 10:56:25.263  8759  8796 I flutter : #84     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1463)
03-21 10:56:25.263  8759  8796 I flutter : #85     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
03-21 10:56:25.263  8759  8796 I flutter : #86     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
03-21 10:56:25.263  8759  8796 I flutter : #87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
03-21 10:56:25.263  8759  8796 I flutter : #88     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
03-21 10:56:25.263  8759  8796 I flutter : #89     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
03-21 10:56:25.263  8759  8796 I flutter : #90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
03-21 10:56:25.263  8759  8796 I flutter : #91     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
03-21 10:56:25.263  8759  8796 I flutter : #92     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
03-21 10:56:25.263  8759  8796 I flutter : #93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
03-21 10:56:25.263  8759  8796 I flutter : #94     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
03-21 10:56:25.263  8759  8796 I flutter : #95     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
03-21 10:56:25.263  8759  8796 I flutter : #96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
03-21 10:56:25.263  8759  8796 I flutter : #97     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
03-21 10:56:25.263  8759  8796 I flutter : #98     RenderBox.layout (package:flutter/src/rendering/box.dart:2389)
03-21 10:56:25.263  8759  8796 I flutter : #99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
03-21 10:56:43.352  8759  8796 I flutter : 2024-03-21 10:56:43.352      INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
03-21 10:56:43.502  8759  8796 I flutter : 2024-03-21 10:56:43.501      INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
03-21 10:57:13.362  8759  8796 I flutter : 2024-03-21 10:57:13.361      INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
03-21 10:57:13.588  8759  8796 I flutter : 2024-03-21 10:57:13.588      INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
03-21 10:57:25.733  8759  8796 I flutter : App either paused or hidden, stopping periodic query for inbox changes.
03-21 10:57:25.740  8759  8759 I SurfaceView@5836b37: onWindowVisibilityChanged(8) false io.flutter.embedding.android.j{5836b37 V.E...... ........ 0,0-1080,2400} of ViewRootImpl@120ee35[MainAc
tivity]
03-21 10:57:25.741  8759  8759 I SurfaceView@5836b37: surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.j{5836b37 V.E...... ........ 0,0-1080,2400}
03-21 10:57:25.803  8759  8759 I SurfaceView@5836b37: windowStopped(true) false io.flutter.embedding.android.j{5836b37 V.E...... ........ 0,0-1080,2400} of ViewRootImpl@120ee35[MainActivity]
03-21 10:57:25.851  8759  8796 I flutter : App either paused or hidden, stopping periodic query for inbox changes.
03-21 10:57:25.851  8759  8796 I flutter : App either paused or hidden, stopping periodic query for inbox changes.
```

### Screenshots

![image](https://github.com/astubenbord/paperless-mobile/assets/5155694/da1cdc65-008a-47e6-a1fe-591faa975fd0)

### Paperless-ng*x Version

2.6.3

### Paperless-Mobile Version

3.2.1

### Device

Samsung Galaxy S21+

### Operating System Version

Android 14

### Device Locale

Dutch or English/United States (tested both)

### Selected Locale

None

**Comment by ErikTempelaarVO** [comment]
Might be related to Samsung / OneUI. I have the same same on Galaxy S23.
S9 with LineageOS doesn't have this issue.

**Comment by astubenbord** [comment]
Yeah, this issue has been reported before on an older version (see #161). This is very likely due to changes in the API of newer versions of paperless where e.g. non-nullable fields have been renamed or made nullable. The app currently does not have support for api v4 and I'm working on an OpenAPI spec to make API versioning easier.
