### ISSUE TITLE
[Bug]: app doesn't support latest api (v5)

### ISSUE THREAD

**Issue by philipp-koch** [astubenbord/paperless-mobile#419]
### What happened?

When I take a look in the app logs, there's a yellow warning telling me that the app doesn't support my server's api yet:
![Screenshot_20240430_002229](https://github.com/astubenbord/paperless-mobile/assets/19315148/42337da4-cc3c-4171-ae75-7fb848ebc864)

* My app version is 3.2.1.
* My PaperlessNGX version is 2.7.2.

While the app seems to work fine, I do have two problems that may or may not be related to this:

1.) ~~When uploading a PDF via sharing it with Paperless Mobile, it sets my user as owner (as expected), but doesn't assign with reading/editing permissions to other users as configured via [Paperless workflow triggers](https://docs.paperless-ngx.com/usage/#workflows) (consumption template). It does work when putting files in the consumption folder on the sever or uploading them via web interface, but unfortunately not when using the app, although "API" is one of the sources set for the workflow in PaperlessNGX's settings. And since your app doesn't show any permissions, just the document owner, I'm guessing that as of now permissions are not supported at all? I mean these here~~ (from PaperlessNGX's web interface):
![Paperless-ngx-berechtigungen](https://github.com/astubenbord/paperless-mobile/assets/19315148/83ca2449-517b-45f2-8dd5-179807dd34d9)

=> This is a classic "kaum macht man's richtig, schon funktioniert's"-situation: **Just after I had written the above, it occurred to me that the permission themselves might [have to be set as a seperate workflow server-side](https://github.com/paperless-ngx/paperless-ngx/discussions/5549), and that's exactly what solves this**: Now, also when uoloading via the app, the permission are being set correctly! Sorry for the false alarm.

2.) When sharing a pdf with the app, I almost always need a second attempt, if the app hasn't been opened for a while (i.e. is not running "in the background" already); the first time, the app just opens, but the document is not uploaded. (Maybe this has to do with my phone's power management? I'm using a Samsung S22 Ultra with no battery setting exception for the app, just the default setting).

PS. Thank you for this great app! It'S what makes PaperlessNGX finally usuable on Android!

### Steps to reproduce

* Share a PDF document with the app
* View its permissions in the web interface ~~(there are none, only the owner is set)~~

### Paperless-ng*x Version

2.7.2

### Paperless-Mobile Version

3.2.1+4053

### Device

Samsung Galaxy S22 Ultra

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

German

**Comment by develroo** [comment]
Ditto. Broken against v5. Can't login. 

```
---BEGIN STACKTRACE---
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ParsedErrorLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:49)
#2      ParsedFormattedLogMessage.consume (package:paperless_mobile/features/logging/models/parsed_log_message.dart:125)
#3      ParsedLogMessage.parse (package:paperless_mobile/features/logging/models/parsed_log_message.dart:14)
#4      AppLogsCubit._updateLogsFromFile (package:paperless_mobile/features/logging/cubit/app_logs_cubit.dart:68)
<asynchronous suspension>

---END STACKTRACE---

```

**Comment by mepi0011** [comment]
Until now, I have been using the paperless app (https://f-droid.org/de/packages/eu.bauerj.paperless_app/).

Now I have seen that there is a newer and more up-to-date app on f-droid (paperless-mobile). Thank's for that!

 When I log in, I get the error message described above.
Is there a description of which authorizations the USER to be logged in needs?

**Comment by cracky22** [comment]
current api is v9

**Comment by astubenbord** [comment]
I'll close this since the latest supported api version is v9 (see https://github.com/astubenbord/paperless-mobile/releases/tag/v4.0.0-beta2)
