### ISSUE TITLE
App crashes when attempting to upload 29 page scan

### ISSUE THREAD

**Issue by QazCetelic** [astubenbord/paperless-mobile#421]
### What happened?

When uploading a decently sized (29 page) scan

### Steps to reproduce

1. Go to scanner
2. Start scanning document
3. Press upload button

### Log output from the app

```shell
Android crashlog

type: crash
osVersion: google/bluejay/bluejay:14/AP1A.240405.002/2024042100:user/release-keys
package: de.astubenbord.paperless_mobile:4053
process: de.astubenbord.paperless_mobile
processUptime: 54058 + 215 ms
installer: org.fdroid.fdroid

java.lang.OutOfMemoryError: Failed to allocate a 159162864 byte allocation with 100663296 free bytes and 102MB until OOM, target footprint 261936768, growth limit 268435456
	at java.lang.StringFactory.newStringFromUtf8Bytes(Native Method)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:94)
	at e4.t.c(Unknown Source:33)
	at e4.f.b(Unknown Source:8)
	at e4.g.e(Unknown Source:2)
	at e4.k$a.a(Unknown Source:6)
	at s3.c.l(Unknown Source:18)
	at s3.c.m(Unknown Source:40)
	at s3.c.i(Unknown Source:0)
	at s3.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```
```


### Screenshots

_No response_

### Paperless-ng*x Version

2.5.3

### Paperless-Mobile Version

3.2.1+4053

### Device

Google Pixel 6a

### Operating System Version

GrapheneOS 14

### Device Locale

US

### Selected Locale

English (US)

### Additional Context

_No response_

**Comment by QazCetelic** [comment]
If anyone else is having this issue, there is a workaround. Exporting the scan to a PDF and then sharing that back to the paperless app does work.

**Comment by thiswillbeyourgithub** [comment]
Pretty sure this is the same issue as what I encountered : #410 

Unfortunately the workaround you mentionned didn't work for me, I had a 50 page document that (I think) got huge (tens or hundreds of MB) and I ended up using [genius scan](https://play.google.com/store/apps/details?id=com.thegrizzlylabs.geniusscan.free) which is an absolute beast (tooks me <1min instead of about 5-10 for the same document!) but is not FOSS so I would really like to not depend on them :)

**Comment by QazCetelic** [comment]
It seems so. I think it would be best to close this issue as duplicate. However, could you first change the title to specify the problem lies with uploading a large amount of pages?

**Comment by thiswillbeyourgithub** [comment]
I renamed my issue, you do yours as I can't do it for you
