### ISSUE TITLE
Stuck on 'Restoring Session'

### ISSUE THREAD

**Issue by ScubyG** [astubenbord/paperless-mobile#436]
### What happened?

When closing the app and reopening it, the Restoring Session screen continously displays with the spinner

### Steps to reproduce

1. Open app
2. Close app
3. Reopen app

### Log output from the app

```shell
---BEGIN ERROR---
S.delegate failed to load unsupported locale "en_GB". This is likely an issue with the localizations generation tool. Please file an issue on GitHub with a reproducible sample app and the gen-l10n configuration that was used.
---END ERROR---
---BEGIN STACKTRACE---
#0      lookupS (package:paperless_mobile/generated/l10n/app_localizations.dart:2566)
#1      _SDelegate.load (package:paperless_mobile/generated/l10n/app_localizations.dart:2537)
#2      AuthenticationCubit.restoreSession (package:paperless_mobile/features/login/cubit/authentication_cubit.dart:283)
#3      _GoRouterShellState.initState.<anonymous closure> (package:paperless_mobile/main.dart:272)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:978)
#7      _rootRun (dart:async/zone.dart:1391)
#8      _CustomZone.run (dart:async/zone.dart:1301)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1209)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#11     _rootRun (dart:async/zone.dart:1399)
#12     _CustomZone.run (dart:async/zone.dart:1301)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233)
#14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

---END STACKTRACE---
2024-07-10 10:41:39.026	INFO    --- [                         ] -                          : Setting refresh rate to 120.00000762939453
```

### Screenshots

![Screenshot_20240710-105123](https://github.com/astubenbord/paperless-mobile/assets/16619574/5a727a48-ff26-44fe-9698-2fe33c7d1901)

### Paperless-ng*x Version

2.10.2

### Paperless-Mobile Version

3.2.1

### Device

Pixel 6 Pro

### Operating System Version

GrapheneOS

### Device Locale

En_GB

### Selected Locale

English (UK)

**Comment by DSchougaard** [comment]
Any updates on this?

**Comment by BeastleeUK** [comment]
I had this issue just now, after being fine for months. I've had to clear the data for the app and log back in. Seems to be something to do with the login process when restoring the session.  Hopefully a one-off.

**Comment by cromelex** [comment]
I am facing this issue now, and it happens every single time the app is reopened. It does not happen with the default en_US locale.

```
2024-12-01 09:05:25.670	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-12-01 09:05:25.670	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Verifying user identity...
2024-12-01 09:05:25.671	ERROR   --- [                         ] - main                     : An unexpected error occurred 
---BEGIN ERROR---
S.delegate failed to load unsupported locale "en_GB". This is likely an issue with the localizations generation tool. Please file an issue on GitHub with a reproducible sample app and the gen-l10n configuration that was used.
---END ERROR---
---BEGIN STACKTRACE---
#0      lookupS (package:paperless_mobile/generated/l10n/app_localizations.dart:2566)
#1      _SDelegate.load (package:paperless_mobile/generated/l10n/app_localizations.dart:2537)
#2      AuthenticationCubit.restoreSession (package:paperless_mobile/features/login/cubit/authentication_cubit.dart:283)
#3      _GoRouterShellState.initState.<anonymous closure> (package:paperless_mobile/main.dart:272)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:978)
#7      _rootRun (dart:async/zone.dart:1391)
#8      _CustomZone.run (dart:async/zone.dart:1301)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1209)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#11     _rootRun (dart:async/zone.dart:1399)
#12     _CustomZone.run (dart:async/zone.dart:1301)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233)
#14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

---END STACKTRACE---
2024-12-01 09:05:25.672	INFO    --- [                         ] -                          : Setting refresh rate to 90.0

```

I've not tried it multiple times and it seems to happen all the time. 
This didn't happen previously.
I did change my setup, so I am now using a .pfx certificate for mTLS.

It works absolutely fine in the default locale, but once it's changed to en_GB (which I do because of the date format), once the app is closed and reopen it gets stuck in this status without any solution.
Clearing cache etc doesn't help. I need to clear all data and relogin from start.

**Comment by gaco79** [comment]
Getting the same here, also only when using .pfx cert. Asked Copilot about this as I've no experience in Flutter apps and it suggested the following:

---

Short answer: it’s not the .pfx itself. You’re hitting a localization edge case that only becomes visible when the mTLS flow is exercised on startup.

Why you only see it with a .pfx
- When a client certificate is configured, the app takes the “restore session” path immediately on launch to set up mTLS and re-auth (AuthenticationCubit.restoreSession). That path shows localized strings like “Restoring session…”, which triggers S.delegate.load very early.
- Your l10n only ships a base English file (intl_en.arb) and no regional English file. With device locale en_GB, the generated delegate claims the language is supported but throws when it can’t load an exact en_GB lookup class.
- Without mTLS you may not hit that early “restore session” path (e.g., no saved account or different timing), so the unsupported-locale exception doesn’t surface.

The underlying fix (independent of mTLS)
- Add a minimal en_GB ARB so the generator emits an en_GB lookup that inherits from base English:

```json name=lib/l10n/intl_en_GB.arb url=https://github.com/astubenbord/paperless-mobile/blob/development/lib/l10n/intl_en_GB.arb
{
  "@@locale": "en_GB"
}
```

- Or add a locale resolution fallback in MaterialApp so en_GB falls back to en:
```dart
localeListResolutionCallback: (locales, supported) {
  for (final locale in (locales ?? const <Locale>[])) {
    if (supported.contains(locale)) return locale;
    final langOnly = Locale(locale.languageCode);
    if (supported.contains(langOnly)) return langOnly;
  }
  return supported.first;
},
```

Notes about the mTLS (.pfx) path
- Your mTLS setup runs at startup when a cert is present (lib/core/security/session_manager_impl.dart), which is why it exposes the l10n issue.
- Separately, consider not calling setTrustedCertificatesBytes with the same .pfx bytes as the client identity. That replaces the default trust store with your client cert, which isn’t a CA and can break TLS validation. Prefer withTrustedRoots/system defaults, and only import the client identity:
  - Use useCertificateChainBytes + usePrivateKeyBytes (or the PKCS#12-capable variants) for the client identity.
  - Avoid setTrustedCertificatesBytes unless you’re explicitly pinning a server CA.

But to your specific question: you only notice the “unsupported locale en_GB” when using a .pfx because mTLS makes the “restore session” path run immediately and trigger localization loading. The root cause is missing/enforced en_GB support in l10n, not the certificate format.
